---
title: "Sesión 01"
date: "2023-01-18"
---

## Materiales

::: {.panel-tabset}

### Clase grabada

**Clase 1: Intro a R RStudio y Quarto**

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/791351489?h=e73209a79f&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sesi&amp;oacute;n 1 - Clase 1: Intro a R, RStudio y Quarto"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>

**Clase 2: Primeros pasos en R**

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/791352672?h=59c806cbaf&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sesi&amp;oacute;n 1 - Clase 2: Primeros pasos en R"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>

### Slides

```{r slides-videos, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))
```

```{r show-slide-tabs1, echo=FALSE, results="asis"}
slide_buttons("/slides/sesion1")
```

```{=html}
<iframe width="780" height="500" src="../slides/sesion1.html" title="Sesión 1"></iframe>
```

### Talleres

- Puede descargar los archivos generados en la carpeta `taller01` en el siguiente enlace: [Aquí](https://drive.google.com/drive/folders/1QLNz-3pHOFa9JxPw5bd3OKLtYv4-PIoL?usp=share_link).


:::


