---
title: "Sesión 02"
date: "2023-01-21"
---

## Materiales

::: {.panel-tabset}

### Clase grabada

**Manejo de datos con R**

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/791559579?h=978d08891a&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sesi&amp;oacute;n 2 - Clase 1: Manejo de datos con R"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>

### Slides

```{r slides-videos, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))
```

```{r show-slide-tabs1, echo=FALSE, results="asis"}
slide_buttons("/slides/sesion2")
```

```{=html}
<iframe width="780" height="500" src="../slides/sesion2.html" title="Sesión 2"></iframe>
```

### Talleres

- Puede descargar los archivos generados en la carpeta `taller02` en el siguiente enlace: [Aquí](https://drive.google.com/drive/folders/1ARE2EPgDGBdf6CWdbPOMZmnxEXJ8YGmk?usp=share_link).


:::


