---
title: "Sesión 03"
date: "2022-01-25"
---

## Materiales

::: {.panel-tabset}

### Clase grabada

**Clase 1: Inspección incial de datos y análisis descriptivo con R**

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/794119967?h=f8b286e328&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sesi&amp;oacute;n 3 - Clase 1: Inspecci&amp;oacute;n inicial de datos"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>

**Clase 2: Visualización de datos con R**

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/795235987?h=2d1dfea124&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sesi&amp;oacute;n 3 - Clase 2: Visualizaci&amp;oacute;n de Datos con ggplot"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>

### Slides

```{r slides-videos, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))
```

```{r show-slide-tabs1, echo=FALSE, results="asis"}
slide_buttons("/slides/sesion3")
```

```{=html}
<iframe width="780" height="500" src="../slides/sesion3.html" title="Sesión 2"></iframe>
```

### Talleres

- Puede descargar los archivos generados en la carpeta `taller03` en el siguiente enlace: [Aquí](https://drive.google.com/drive/folders/15PoGF3KDwiDXYxm6n2t6SNaF7LS49A7t?usp=share_link).


:::




