---
title: "Sesión 04"
date: "2022-01-28"
---

## Materiales

::: {.panel-tabset}

### Clase grabada

**Clase 1: Inferencia Estadística (parte 1)**

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/795965879?h=2fc03d34af&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sesi&amp;oacute;n 4 - Clase 1: Inferencia Estad&amp;iacute;stica"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>

**Clase 2: Inferencia Estadística (parte 2)**

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/795959533?h=470e66a6d3&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sesi&amp;oacute;n 4 - Clase 2: Inferencia Estad&amp;iacute;stica"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>

**Clase 3: Regresión**

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/803534451?h=2cd8076ce8&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sesi&amp;oacute;n 4 - Clase 3: Regresi&amp;oacute;n"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>

### Slides

```{r slides-videos, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))
```

```{r show-slide-tabs1, echo=FALSE, results="asis"}
slide_buttons("/slides/sesion4")
```

```{=html}
<iframe width="780" height="500" src="../slides/sesion4.html" title="Sesión 2"></iframe>
```

### Talleres

- Puede descargar los archivos generados en la carpeta `taller02` en el siguiente enlace: [Aquí](https://drive.google.com/drive/folders/18PHD4uNhXBJVKyLxfl6q9XoYx0ax9hXG?usp=sharing).


:::


